// Assignment Code
// Here multiple variables and arrays are being declared
var generateBtn = document.querySelector("#generate");
var lowerCase = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];
var upperCase = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
var numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
var specialChar = [
  "!",
  "#",
  "$",
  "%",
  "&",
  "(",
  ")",
  "*",
  "+",
  "/",
  "<",
  ">",
  "?",
  "@",
];

// Write password to the #password input
// on button click the writePassword function executes
// first password is equal to the return value of the function generatePassword
// after generatePassword executes, passwordText = anything in our .html that has an id of password
// lastly, the value of passwordText and password are equal
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");
  passwordText.value = password;
  // or
  // document.querySelector("#password").value = generatePassword();
}

function generatePassword() {
  // declares passwordLength to be the value of the prompt and creates two empty arrays
  var passwordLength = prompt("Password Length (8-128)");
  var possibleArray = [];
  var displayPassword = [];

  // an alert if values did not equal 8 through 128
  if (passwordLength < 8 || passwordLength > 128) {
    alert("Enter a number between 8 and 128.");
    return;
  }

  // boolean variables created to record user inputs of character selection
  var blnLowerCase = confirm("Include lower case letters?");
  var blnUpperCase = confirm("Include upper case letters?");
  var blnNumbers = confirm("Include numbers?");
  var blnSpecialChar = confirm("Include special characters?");

  // if the boolean variables are true, then add all values of that array into an empty array; combining arrays.
  if (blnLowerCase) {
    possibleArray = possibleArray.concat(lowerCase);
  }
  if (blnUpperCase) {
    possibleArray = possibleArray.concat(upperCase);
  }
  if (blnNumbers) {
    possibleArray = possibleArray.concat(numbers);
  }
  if (blnSpecialChar) {
    possibleArray = possibleArray.concat(specialChar);
  }

  // creates a variable passwordIndex to be equal to a random integer between the values of possibleArray.length.
  // creates a variable displayPassword to be equal to itself, and add on a  character from possibleArray at the random index generated by passwordIndex
  for (var i = 0; i < passwordLength; i++) {
    passwordIndex = Math.floor(Math.random() * possibleArray.length);
    displayPassword = displayPassword.concat(possibleArray[passwordIndex]);
  }

  // sets displayPassword to be equal to itself where the individual possible values are not separated by anything. Commenting this out will put , between each value.
  displayPassword = displayPassword.join("");

  // if you select no boolean value (no lower, upper, number, or special char) to be true then you will get an alert to choose one
  // lastly, return the value of displayPassword.
  if (
    blnLowerCase != true &&
    blnUpperCase != true &&
    blnNumbers != true &&
    blnSpecialChar != true
  ) {
    alert("Your password needs to have some characters!");
    return;
  } else {
    return displayPassword;
  }
}

// Add event listener to generate button
// On click of the generateBtn, the function write password executes
generateBtn.addEventListener("click", writePassword);
